# Generated by Django 3.2.7 on 2021-09-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
        ('task', '0003_alter_task_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, through='task.TaskLabel', to='label.Label', verbose_name='labels'),
        ),
    ]
