# Generated by Django 3.2.7 on 2021-09-08 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_status_created_at'),
        ('task', '0005_alter_tasklabel_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='status.status'),
        ),
    ]
