# Generated by Django 3.2.7 on 2021-09-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_alter_tasklabel_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='name'),
        ),
    ]
