# Generated by Django 3.2.7 on 2021-09-09 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that email already exists.'}, help_text='Your email must exists and be unique.', max_length=150, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='email'),
        ),
    ]
