# Generated by Django 3.2.6 on 2021-08-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='created_at',
            field=models.DateField(auto_now_add=True, default='2021-01-01'),
            preserve_default=False,
        ),
    ]
